version: "3.8"
services:
  api:
    image: express/be-kelas-programmer:1.0.0
    build: .
    container_name: be-kp
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules